export const transitData = [
  {
    trackingNumber: "number sample",
    client: "client sample",
    manufacturer: "Honda",
    plateNumber: "ABC 123",
  },
  {
    trackingNumber: "number sample",
    client: "client sample",
    manufacturer: "Honda",
    plateNumber: "ABC 123",
  },
  {
    trackingNumber: "number sample",
    client: "client sample",
    manufacturer: "Honda",
    plateNumber: "ABC 123",
  },
  {
    trackingNumber: "number sample",
    client: "client sample",
    manufacturer: "Honda",
    plateNumber: "ABC 123",
  },
];

export const driverData = [
  {
    id: 1,
    name: "Juan",
    status: "Available",
    plateNumber: "ABC 123",
    driverPicture: "/src/assets/driverPic1.svg",
  },
  {
    id: 2,
    name: "Juan2",
    status: "Available",
    plateNumber: "ABC 123",
    driverPicture: "/src/assets/driverPic1.svg",
  },
  {
    id: 3,
    name: "Juan3",
    status: "Available",
    plateNumber: "ABC 123",
    driverPicture: "/src/assets/driverPic1.svg",
  },
  {
    id: 4,
    name: "Juan4",
    status: "Available",
    plateNumber: "ABC 123",
    driverPicture: "/src/assets/driverPic1.svg",
  },
];
export const tripsData = [
  {
    id: 1,
    trackingNumber: "TF0123456789",
    status: "On Checking",
    client: "Juan Dela Cruz",
    manufacturer: "HONDA",
    plateNumber: "ABC 124",
    datePlaced: "March 13, 2024",
    dateScheduled: "March 20, 2024",
    pickUpLocation:
      "839 unit-N S. H. Loyola, Sampaloc, Manila, 1008 Metro Manila",
    dropOffLocation: "Espana, Manila City, Metro Manila, Philippines",
  },
  {
    id: 2,
    trackingNumber: "TF9876543210",
    status: "In Transit",
    client: "Maria Garcia",
    manufacturer: "TOYOTA",
    plateNumber: "XYZ 789",
    datePlaced: "March 15, 2024",
    dateScheduled: "March 22, 2024",
    pickUpLocation: "123 Main St, Quezon City, Metro Manila",
    dropOffLocation: "Ortigas Center, Pasig City, Metro Manila, Philippines",
  },
  {
    id: 3,
    trackingNumber: "TF2468135790",
    status: "Delivered",
    client: "John Smith",
    manufacturer: "FORD",
    plateNumber: "DEF 456",
    datePlaced: "March 18, 2024",
    dateScheduled: "March 25, 2024",
    pickUpLocation: "456 Elm St, Makati City, Metro Manila",
    dropOffLocation:
      "Bonifacio Global City, Taguig City, Metro Manila, Philippines",
  },
  {
    id: 4,
    trackingNumber: "TF2468135790",
    status: "Cancelled",
    client: "John Smith",
    manufacturer: "FORD",
    plateNumber: "DEF 456",
    datePlaced: "March 18, 2024",
    dateScheduled: "March 25, 2024",
    pickUpLocation: "456 Elm St, Makati City, Metro Manila",
    dropOffLocation:
      "Bonifacio Global City, Taguig City, Metro Manila, Philippines",
  },
];
export const scheduleData = [
  {
    id: 1,
    trackingNumber: "TF0123456789",
    status: "In transit",
    client: "Juan Dela Cruz",
    manufacturer: "HONDA",
    plateNumber: "ABC 124",
    datePlaced: "March 13, 2024",
    dateScheduled: "March 20, 2024",
    pickUpLocation:
      "839 unit-N S. H. Loyola, Sampaloc, Manila, 1008 Metro Manila",
    dropOffLocation: "Espana, Manila City, Metro Manila, Philippines",
  },
  {
    id: 2,
    trackingNumber: "TF0234567890",
    status: "In transit",
    client: "Maria Santos",
    manufacturer: "Toyota",
    plateNumber: "XYZ 456",
    datePlaced: "March 15, 2024",
    dateScheduled: "March 22, 2024",
    pickUpLocation: "123 Main St, Quezon City, Metro Manila, Philippines",
    dropOffLocation: "Makati City, Metro Manila, Philippines",
  },
  {
    id: 3,
    trackingNumber: "TF0345678901",
    status: "In transit",
    client: "Pedro Morales",
    manufacturer: "Ford",
    plateNumber: "DEF 789",
    datePlaced: "March 17, 2024",
    dateScheduled: "March 24, 2024",
    pickUpLocation: "456 Elm St, Pasig City, Metro Manila, Philippines",
    dropOffLocation: "Alabang, Muntinlupa, Metro Manila, Philippines",
  },
  // Add more entries as needed
];
export const historyData = [
  {
    id: 1,
    trackingNumber: "TF0123456789",
    status: "Received",
    client: "Juan Dela Cruz",
    manufacturer: "HONDA",
    plateNumber: "ABC 124",
    datePlaced: "March 13, 2024",
    dateScheduled: "March 20, 2024",
    pickUpLocation:
      "839 unit-N S. H. Loyola, Sampaloc, Manila, 1008 Metro Manila",
    dropOffLocation: "Espana, Manila City, Metro Manila, Philippines",
  },
  {
    id: 2,
    trackingNumber: "TF0234567890",
    status: "Received",
    client: "Maria Santos",
    manufacturer: "Toyota",
    plateNumber: "XYZ 456",
    datePlaced: "March 15, 2024",
    dateScheduled: "March 22, 2024",
    pickUpLocation: "123 Main St, Quezon City, Metro Manila, Philippines",
    dropOffLocation: "Makati City, Metro Manila, Philippines",
  },
  {
    id: 3,
    trackingNumber: "TF0345678901",
    status: "Received",
    client: "Pedro Morales",
    manufacturer: "Ford",
    plateNumber: "DEF 789",
    datePlaced: "March 17, 2024",
    dateScheduled: "March 24, 2024",
    pickUpLocation: "456 Elm St, Pasig City, Metro Manila, Philippines",
    dropOffLocation: "Alabang, Muntinlupa, Metro Manila, Philippines",
  },
];
